--Create Container
CALL _SYS_DI#SYS_XS_HANA_BROKER.CREATE_CONTAINER('HDI_WITHOUT_XSA', _SYS_DI.T_NO_PARAMETERS, ?, ?, ?);

--Grant Container to Development User(s)
CREATE LOCAL TEMPORARY COLUMN TABLE #PRIVILEGES LIKE _SYS_DI.TT_API_PRIVILEGES; 
INSERT INTO #PRIVILEGES (PRINCIPAL_NAME, PRIVILEGE_NAME, OBJECT_NAME) SELECT 'WORKSHOP_00', PRIVILEGE_NAME, OBJECT_NAME FROM _SYS_DI.T_DEFAULT_CONTAINER_ADMIN_PRIVILEGES; 
CALL _SYS_DI#SYS_XS_HANA_BROKER.GRANT_CONTAINER_API_PRIVILEGES('HDI_WITHOUT_XSA', #PRIVILEGES, _SYS_DI.T_NO_PARAMETERS, ?, ?, ?); 
DROP TABLE #PRIVILEGES;

--Configure Default Libraries for Container
CALL HDI_WITHOUT_XSA#DI.CONFIGURE_LIBRARIES(_SYS_DI.T_DEFAULT_LIBRARIES, _SYS_DI.T_NO_PARAMETERS, ?, ?, ?);

-- To Drop
-- CALL _SYS_DI#SYS_XS_HANA_BROKER.DROP_CONTAINER('HDI_WITHOUT_XSA', _SYS_DI.T_NO_PARAMETERS, ?, ?, ?);

--CALL HDI_WITHOUT_XSA#DI.LIST_CONFIGURED_LIBRARIES(_SYS_DI.T_NO_PARAMETERS, ?, ?, ?, ?); 